### PR TITLE
Fix: Edit/delete sends the proper update to followers

### LINKED ISSUE #104: Fix: MoodEventService update feed on delete/edit
**Description:** 
Deleting or editing a mood doesn't update the feed of followers. Change it to do so.

**Rationale:** 
So that I can accurately see the most recent mood event of the users i follow

### PR DESCRIPTION
**Pull request by bojotamara**
Closes #104 

**Summary**
Before, editing or deleting the most recent mood event didn't send updates to followers. Now it puts it into their feed.

### CODE REVIEW

File: Moodlet/app/src/main/java/com/cmput3owo1/moodlet/services/MoodEventService.java [hunk 1]
```diff
@@ -116,15 +100,52 @@ public void onComplete(@NonNull Task<QuerySnapshot> task) {
...
+                        updateFollowersFeed(moodEvent);
+                    }
+                }
+            }
+        });
+
         listener.onMoodUpdateSuccess();
+    }
+
+    private void updateFollowersFeed(final MoodEvent moodEvent) {
```
Comment (WJXHenry) [inline Moodlet/app/src/main/java/com/cmput3owo1/moodlet/services/MoodEventService.java:133]: Please include Javadoc for this function

**Review by WJXHenry — CHANGES_REQUESTED** [review]
Looks good! Just needs Javadoc for the `updateFollowersFeed` function

**Review by WJXHenry — APPROVED** [review]
LGTM
